# Generated by Django 6.1.1 on 2026-09-04 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebPushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('player_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('browser', models.CharField(blank=True, default='Chrome', max_length=50)),
                ('endpoint', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webpush_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'web_push_subscriptions',
                'indexes': [models.Index(fields=['user'], name='web_push_su_user_id_a9f08a_idx')],
            },
        ),
    ]
